"""add_phase1_tables_step1_6_to_1_10

Revision ID: 9c09c6dd0d22
Revises: e9e4b716c64c
Create Date: 2026-03-03 15:50:10.983029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '9c09c6dd0d22'
down_revision: Union[str, None] = 'e9e4b716c64c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotion_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Unicode(length=30), nullable=False, comment='Tag display name'),
    sa.Column('dimension', mssql.TINYINT(), nullable=False, comment='1=Stress/Anxiety 2=Joy/Reward 3=Boredom/Habit 4=Social-driven'),
    sa.Column('is_system', sa.Boolean(), server_default='1', nullable=False, comment='True = system preset; False = user-defined'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('analysis_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('report_type', mssql.TINYINT(), nullable=False, comment='1=Weekly 2=Monthly 3=Yearly'),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('ai_role', sa.String(length=30), nullable=False, comment='behavior_doctor / structure_analyst / life_planner'),
    sa.Column('summary', sa.Unicode(), nullable=False, comment='AI-generated summary text'),
    sa.Column('health_score', mssql.TINYINT(), nullable=True, comment='Financial health score 0-100, yearly reports only'),
    sa.Column('detail_json', sa.Unicode(), nullable=False, comment='Full analysis data in JSON format'),
    sa.Column('prompt_used', sa.String(length=50), nullable=False, comment='MCP Prompt template name used for generation'),
    sa.Column('skills_invoked', sa.Unicode(length=500), nullable=True, comment='JSON array of invoked skill IDs for audit'),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False, comment='e.g. budget.modify, goal.adjust_timeline, budget.emergency_spread'),
    sa.Column('target_entity', sa.String(length=50), nullable=False, comment='e.g. Budget, SavingGoal'),
    sa.Column('target_id', sa.BigInteger(), nullable=False, comment='ID of the operated entity'),
    sa.Column('before_snapshot', sa.Unicode(), nullable=False, comment='Pre-operation data snapshot (JSON)'),
    sa.Column('after_snapshot', sa.Unicode(), nullable=False, comment='Post-operation data snapshot (JSON)'),
    sa.Column('trigger_source', sa.String(length=30), nullable=False, comment='user_manual / agent_confirmed / system_auto'),
    sa.Column('agent_session_id', sa.String(length=100), nullable=True, comment='Agent conversation session ID if triggered by Agent'),
    sa.Column('is_rolled_back', sa.Boolean(), server_default='0', nullable=False, comment='Whether this operation has been rolled back'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('base_date', sa.Date(), nullable=False, comment='Snapshot baseline date'),
    sa.Column('scenario', sa.Unicode(length=500), nullable=False, comment='User-provided scenario description'),
    sa.Column('snapshot_data', sa.Unicode(), nullable=False, comment='Full ledger state at base_date (JSON)'),
    sa.Column('simulation_params', sa.Unicode(), nullable=False, comment='Simulation parameter set (JSON)'),
    sa.Column('results_json', sa.Unicode(), nullable=False, comment='Multi-plan simulation results (JSON)'),
    sa.Column('chosen_plan', mssql.TINYINT(), nullable=True, comment='User-selected plan number (NULL = not chosen)'),
    sa.Column('applied', sa.Boolean(), server_default='0', nullable=False, comment='Whether the chosen plan has been applied to real ledger'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spread_plans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source_year_month', sa.Unicode(length=7), nullable=False, comment='Original month that triggered the spread, e.g. 2026-03'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total amount to be spread'),
    sa.Column('monthly_deduction', sa.Numeric(precision=12, scale=2), nullable=False, comment='Amount deducted from flexible pool each month'),
    sa.Column('remaining_months', mssql.TINYINT(), nullable=False, comment='Remaining months to deduct'),
    sa.Column('total_months', mssql.TINYINT(), nullable=False, comment='Total spread duration in months'),
    sa.Column('description', sa.Unicode(length=200), nullable=True, comment='Reason for the spread'),
    sa.Column('status', mssql.TINYINT(), server_default='1', nullable=False, comment='1=InProgress 2=Completed 3=Cancelled'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_spread_plans_user_status', 'spread_plans', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spread_plans_user_status', table_name='spread_plans')
    op.drop_table('spread_plans')
    op.drop_table('simulation_snapshots')
    op.drop_table('operation_logs')
    op.drop_table('analysis_reports')
    op.drop_table('emotion_tags')
    # ### end Alembic commands ###
