"""add_phase1_tables_step1_1_to_1_5

Revision ID: e9e4b716c64c
Revises: 0b3bd701045d
Create Date: 2026-03-03 14:52:00.993486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'e9e4b716c64c'
down_revision: Union[str, None] = '0b3bd701045d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.Unicode(length=50), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('monthly_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('payday', mssql.TINYINT(), nullable=True, comment='Pay day of month (1-31)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('budgets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('year_month', sa.String(length=7), nullable=False, comment='Format YYYY-MM, e.g. 2026-03'),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Fixed pool allocation'),
    sa.Column('flexible_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Flexible pool allocation'),
    sa.Column('emergency_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Emergency pool allocation'),
    sa.Column('spread_deduction', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False, comment='Amount deducted from flexible pool due to spread plans'),
    sa.Column('expected_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', mssql.TINYINT(), server_default='1', nullable=False, comment='1=Active 2=Settled'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year_month', name='uq_budgets_user_month')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='NULL = system preset; non-NULL = user-defined'),
    sa.Column('name', sa.Unicode(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='Self-referencing FK for two-level hierarchy'),
    sa.Column('pool_type', mssql.TINYINT(), nullable=False, comment='1=Fixed 2=Flexible 3=Emergency'),
    sa.Column('type', mssql.TINYINT(), nullable=False, comment='1=Expense 2=Income 3=General'),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saving_goals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('monthly_saving', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('priority', mssql.TINYINT(), nullable=False, comment='1=Highest priority'),
    sa.Column('allocation_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage of annual savings allocated to this goal'),
    sa.Column('status', mssql.TINYINT(), server_default='1', nullable=False, comment='1=InProgress 2=Completed 3=Abandoned'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_pools',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('budget_id', sa.BigInteger(), nullable=False),
    sa.Column('pool_type', mssql.TINYINT(), nullable=False, comment='1=Fixed 2=Flexible 3=Emergency'),
    sa.Column('allocated_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('spent_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_id', 'pool_type', name='uq_budget_pools_budget_type')
    )
    op.create_table('goal_milestones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('goal_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', mssql.TINYINT(), server_default='1', nullable=False, comment='1=Pending 2=InProgress 3=Completed'),
    sa.ForeignKeyConstraint(['goal_id'], ['saving_goals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', mssql.TINYINT(), nullable=False, comment='1=Expense 2=Income'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Always positive'),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('merchant', sa.Unicode(length=100), nullable=True),
    sa.Column('description', sa.Unicode(length=500), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('transaction_time', sa.Time(), nullable=True),
    sa.Column('source', mssql.TINYINT(), nullable=False, comment='1=Manual 2=OCR 3=Voice 4=BulkImport'),
    sa.Column('emotion_tags', sa.Unicode(length=500), nullable=True, comment='JSON array of emotion tag names'),
    sa.Column('is_recurring', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_user_date', 'transactions', ['user_id', 'transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('goal_milestones')
    op.drop_table('budget_pools')
    op.drop_table('saving_goals')
    op.drop_table('categories')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
